episodios = {
  "2023-06-27-001" : {
    "nome" : "#10 PODCAST - HACK TOWN SANTA RITA DO SAPUCAÍ",
    "produtoras" : ["Novo Comércio Cast"],
    "programa" : "Novo Comércio Cast",
    "formato" : "vídeo",
    "data" : "2023-06-27",
    "duracao" : 52,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=0mRxtrYRI7g",
    "img" : "https://i.ytimg.com/vi/0mRxtrYRI7g/hqdefault.jpg"
  },
  "2023-07-02-001" : {
    "nome" : "Hack Town: Inovação, Diversidade e Transformação da Sociedade //The Moon Cast Ep. 8 // João Rubens",
    "produtoras" : ["The Moon Cast"],
    "programa" : "Moon Cast",
    "formato" : "vídeo",
    "data" : "2023-07-02",
    "duracao" : 73,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=3MnPVxrlB7U",
    "img" : "https://i.ytimg.com/vi/3MnPVxrlB7U/hqdefault.jpg"
  },
  "2023-08-07-001" : {
    "nome" : "Aceitar a abundância, com Marcos David ",
    "produtoras" : ["Claudia Online"],
    "programa" : "Jornada da Calma",
    "formato" : "audio",
    "data" : "2023-08-07",
    "duracao" : 36,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=ahLtLKA-nTg",
    "img" : "https://i.ytimg.com/vi/ahLtLKA-nTg/hqdefault.jpg"
  },
  "2023-08-07-002" : {
    "nome" : "MOBs no HackTown 2023",
    "produtoras" : ["Transcriativa"],
    "programa" : "Transcriativa",
    "formato" : "vídeo",
    "data" : "2023-08-07",
    "duracao" : 9,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=LtNmf222Xfc",
    "img" : "https://i.ytimg.com/vi/LtNmf222Xfc/hqdefault.jpg"
  },
  "2023-08-12-001" : {
    "nome" : "Coolab Innovation Especial Hacktown 2023 – Conheça mais sobre o Hacktalks by Compasso",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Coolab Innovation",
    "formato" : "vídeo",
    "data" : "2023-08-12",
    "duracao" : 46,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=A6ssRHudI8s",
    "img" : "https://img.youtube.com/vi/A6ssRHudI8s/maxresdefault.jpg"
  },
  "2023-08-15-001" : {
    "nome" : "Coolab Innovation Especial Hacktonw 2023 – A NAV pousará no Hacktown 2023, embarque agora!",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Coolab Innovation",
    "formato" : "vídeo",
    "data" : "2023-08-15",
    "duracao" : 67,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=Rwm41BuiVIU",
    "img" : "https://img.youtube.com/vi/Rwm41BuiVIU/maxresdefault.jpg"
  },
  "2023-08-17-001" : {
    "nome" : "AO VIVO DO HACKTOWN",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Coolab Innovation",
    "formato" : "vídeo",
    "data" : "2023-08-17",
    "duracao" : 20,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=p6S_y1e8e4I",
    "img" : "https://img.youtube.com/vi/p6S_y1e8e4I/maxresdefault.jpg"
  },
  "2023-08-17-002" : {
    "nome" : "Coolab Innovation especial Hacktown 2023 - 17-ago-2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Coolab Innovation",
    "formato" : "vídeo",
    "data" : "2023-08-17",
    "duracao" : 45,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=xZvhazmM0wg",
    "img" : "https://img.youtube.com/vi/xZvhazmM0wg/maxresdefault.jpg"
  },
  "2023-08-17-003" : {
    "nome" : "Giro Hacktalks by Compasso Coolab - 17ago2023 - 1a edição",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Giro Hacktalks",
    "formato" : "vídeo",
    "data" : "2023-08-17",
    "duracao" : 3,
    "plataformas" : ["YouTube","Instagram"],
    "link" : "https://www.youtube.com/watch?v=Dfw1fuuR_FM",
    "img" : "https://img.youtube.com/vi/Dfw1fuuR_FM/maxresdefault.jpg"
  },
  "2023-08-17-004" : {
    "nome" : "Giro Hacktalks by Compasso Coolab - 17ago2023 - 2a edição",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Giro Hacktalks",
    "formato" : "vídeo",
    "data" : "2023-08-17",
    "duracao" : 6,
    "plataformas" : ["YouTube","Instagram"],
    "link" : "https://www.youtube.com/watch?v=UgW09W-OdYM",
    "img" : "https://img.youtube.com/vi/UgW09W-OdYM/maxresdefault.jpg"
  },
  "2023-08-17-005" : {
    "nome" : "Hack Town - Santa Cruz Leva Você com Desconto",
    "produtoras" : ["Santa Cruz"],
    "programa" : "Rádio Ônibus",
    "formato" : "audio",
    "data" : "2023-08-17",
    "duracao" : 22,
    "plataformas" : ["Spotify"],
    "link" : "https://open.spotify.com/episode/5taRNEhSpMebHhRF0XHu7X",
    "img" : "https://a88092df6f.clvaw-cdnwnd.com/58fd5d61a00ab4f3d25eaafde57263e5/200006356-03aca03acd/HACK%20TOWN.webp?ph=a88092df6f"
  },
  "2023-08-18-001" : {
    "nome" : "Coolab Innovation especial Hacktown 2023 - 18-ago-2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Coolab Innovation",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 45,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=3JSuuYRqP38",
    "img" : "https://img.youtube.com/vi/3JSuuYRqP38/maxresdefault.jpg"
  },
  "2023-08-18-002" : {
    "nome" : "Giro Hacktalks by Compasso Coolab - 18ago2023 - 1a edição",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Giro Hacktalks",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 5,
    "plataformas" : ["YouTube","Instagram"],
    "link" : "https://www.youtube.com/watch?v=Xb8sDtQMrWE",
    "img" : "https://img.youtube.com/vi/Xb8sDtQMrWE/maxresdefault.jpg"
  },
  "2023-08-18-003" : {
    "nome" : "Giro Hacktalks by Compasso Coolab - 18ago2023 - 2a edição",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Giro Hacktalks",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 4,
    "plataformas" : ["YouTube","Instagram"],
    "link" : "https://www.youtube.com/watch?v=VdZ7rYz8UzM",
    "img" : "https://img.youtube.com/vi/VdZ7rYz8UzM/maxresdefault.jpg"
  },
  "2023-08-18-004" : {
    "nome" : "Gabriela Oliveira e Milena Ferreira No Hacktown 2023 - Rock Night Podcast #01",
    "produtoras" : ["Rock Night","Conta pro Queiroz"],
    "programa" : "Rock Night",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 56,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=WN18-ZLmMo8",
    "img" : "https://i.ytimg.com/vi/WN18-ZLmMo8/hqdefault.jpg"
  },
  "2023-08-18-005" : {
    "nome" : "Moon Walking: The Moon Cast aterrissa no Hack Town",
    "produtoras" : ["The Moon Cast"],
    "programa" : "Moon Cast",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 61,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=_WfLsFCdODM",
    "img" : "https://img.youtube.com/vi/_WfLsFCdODM/maxresdefault.jpg"
  },
  "2023-08-18-006" : {
    "nome" : "🔥TrenDs News🚀 #93 - HackTown 2023 Futuro da Educação ",
    "produtoras" : ["🚀 TrenDs News 🔥"],
    "programa" : "🚀 TrenDs News 🔥",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 87,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=PRfF8C2kxlI",
    "img" : "https://i.ytimg.com/vi/PRfF8C2kxlI/hqdefault.jpg"
  },
  "2023-08-18-007" : {
    "nome" : "Como sua história aumenta sua grandeza?",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 40,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=-f12FViDAqg",
    "img" : "https://img.youtube.com/vi/-f12FViDAqg/maxresdefault.jpg"
  },
  "2023-08-18-008" : {
    "nome" : "Onde posso chegar quando me conecto às pessoas certas?",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 53,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=eQaMiw-EcaQ",
    "img" : "https://i.ytimg.com/vi/eQaMiw-EcaQ/hqdefault.jpg"
  },
  "2023-08-18-009" : {
    "nome" : "Liderança desnecesásria",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 43,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=2Ijs-vZkVbw",
    "img" : "https://i.ytimg.com/vi/2Ijs-vZkVbw/hqdefault.jpg"
  },
  "2023-08-18-010" : {
    "nome" : "Borogodó brasileiro: unindo forças para servir o mundo",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 37,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=tg2ZkhYM4ng",
    "img" : "https://i.ytimg.com/vi/tg2ZkhYM4ng/hqdefault.jpg"
  },
  "2023-08-18-011" : {
    "nome" : "Coragem, quanto mais a gente usa, mais a gente tem.",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 48,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=5U5E-y9kIqs",
    "img" : "https://i.ytimg.com/vi/5U5E-y9kIqs/hqdefault.jpg"
  },
  "2023-08-18-012" : {
    "nome" : "Como equilibrar criatividade, sustentabilidade e lucro?",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 45,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=NP64XqylX_Y",
    "img" : "https://i.ytimg.com/vi/NP64XqylX_Y/hqdefault.jpg"
  },
  "2023-08-18-013" : {
    "nome" : "Reputação como moeda de valor",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 45,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=3LDt5b66Yl4",
    "img" : "https://i.ytimg.com/vi/3LDt5b66Yl4/hqdefault.jpg"
  },
  "2023-08-18-014" : {
    "nome" : "Seu negócio está pronto para a Economia Curativa?",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-18",
    "duracao" : 45,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=u6M1JgTIxbY",
    "img" : "https://i.ytimg.com/vi/u6M1JgTIxbY/hqdefault.jpg"
  },
  "2023-08-19-001" : {
    "nome" : "Hacktalks em 15 minutos com Ester Souza, direto do Hacktown 2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Hacktalks em 15 minutos",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 15,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=2PEs3j7CIVw",
    "img" : "https://img.youtube.com/vi/2PEs3j7CIVw/maxresdefault.jpg"
  },
  "2023-08-19-002" : {
    "nome" : "Hacktalks em 15 minutos com Gisele Ferreira, direto do Hacktown 2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Hacktalks em 15 minutos",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 15,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=_pazLaBBJB4",
    "img" : "https://img.youtube.com/vi/_pazLaBBJB4/maxresdefault.jpg"
  },
  "2023-08-19-003" : {
    "nome" : "Hacktalks em 15 minutos com Ana Cristina, direto do Hacktown 2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Hacktalks em 15 minutos",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 15,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=EFF_r-mozVk",
    "img" : "https://i.ytimg.com/vi/EFF_r-mozVk/hqdefault.jpg"
  },
  "2023-08-19-004" : {
    "nome" : "Hacktalks em 15 minutos com Alberto Roitman, direto do Hacktown 2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Hacktalks em 15 minutos",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 15,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=DTzqB7plCIA",
    "img" : "https://img.youtube.com/vi/DTzqB7plCIA/maxresdefault.jpg"
  },
  "2023-08-19-005" : {
    "nome" : "Coolab Innovation especial Hacktown 2023 - 19-ago-2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Coolab Innovation",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 91,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=2oirZFkKD4g",
    "img" : "https://img.youtube.com/vi/2oirZFkKD4g/maxresdefault.jpg"
  },
  "2023-08-19-006" : {
    "nome" : "Giro Hacktalks by Compasso Coolab - 19ago2023 - 1a edição",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Giro Hacktalks",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 3,
    "plataformas" : ["YouTube","Instagram"],
    "link" : "https://www.youtube.com/watch?v=hIxkbo73Sg8",
    "img" : "https://img.youtube.com/vi/hIxkbo73Sg8/maxresdefault.jpg"
  },
  "2023-08-19-007" : {
    "nome" : "Giro Hacktalks by Compasso Coolab - 19ago2023 - 2a edição",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Giro Hacktalks",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 2,
    "plataformas" : ["YouTube","Instagram"],
    "link" : "https://www.youtube.com/watch?v=zD3k59WhKWY",
    "img" : "https://img.youtube.com/vi/zD3k59WhKWY/maxresdefault.jpg"
  },
  "2023-08-19-008" : {
    "nome" : "Sheylli Caleffi e Rapha Albino No Hacktown 2023 - Rock Night Podcast #02",
    "produtoras" : ["Rock Night","Conta pro Queiroz"],
    "programa" : "Rock Night",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 56,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=mraQFK1zzNM",
    "img" : "https://i.ytimg.com/vi/mraQFK1zzNM/hqdefault.jpg"
  },
  "2023-08-19-009" : {
    "nome" : "InaTalks - Conexões que transformam - Educação, tecnologia e colaboração para inovar",
    "produtoras" : ["Inatel"],
    "programa" : "InaTalks",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 53,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=Y7qkJj7pSCU",
    "img" : "https://i.ytimg.com/vi/Y7qkJj7pSCU/hqdefault.jpg"
  },
  "2023-08-19-010" : {
    "nome" : "Jornada da Liderança Ao Vivo do HackTown 2023",
    "produtoras" : ["Jornada da Liderança","Valide.se"],
    "programa" : "Jornada da Liderança",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 54,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/live/wHhxbPDSAyw?feature=share&t=136",
    "img" : "https://i.ytimg.com/vi/wHhxbPDSAyw/hqdefault.jpg"
  },
  "2023-08-19-011" : {
    "nome" : "Studio Valide-se no Hacktown 2023",
    "produtoras" : ["Valide.se"],
    "programa" : "Estúdio Valide.se",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 26,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=POaudrqgWI4",
    "img" : "https://i.ytimg.com/vi/POaudrqgWI4/hqdefault.jpg"
  },
  "2023-08-19-012" : {
    "nome" : "Studio Valide-se no Hacktown 2023",
    "produtoras" : ["Valide.se"],
    "programa" : "Estúdio Valide.se",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 35,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=EQxhvwzcTLY",
    "img" : "https://i.ytimg.com/vi/EQxhvwzcTLY/hqdefault.jpg"
  },
  "2023-08-19-013" : {
    "nome" : "Inovação e Tecnologias originárias",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 35,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=fUHJ7VmzmSg",
    "img" : "https://i.ytimg.com/vi/fUHJ7VmzmSg/hqdefault.jpg"
  },
  "2023-08-19-014" : {
    "nome" : "O que muda quando uma mulher lidera uma ideia?",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 40,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=B2AQ6ZBc5qA",
    "img" : "https://i.ytimg.com/vi/B2AQ6ZBc5qA/hqdefault.jpg"
  },
  "2023-08-19-015" : {
    "nome" : "Borogodó como patrimônio imaterial brasileiro",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 40,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=rmzBed2-inI",
    "img" : "https://i.ytimg.com/vi/rmzBed2-inI/hqdefault.jpg"
  },
  "2023-08-19-016" : {
    "nome" : "Afinal, ODS serve pra quê?",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 46,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=EDsOMW6Geh0",
    "img" : "https://i.ytimg.com/vi/EDsOMW6Geh0/hqdefault.jpg"
  },
  "2023-08-19-017" : {
    "nome" : "O valor da marca Brasil no mundo",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 56,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=b67kRMAqGlc",
    "img" : "https://i.ytimg.com/vi/b67kRMAqGlc/hqdefault.jpg"
  },
  "2023-08-19-018" : {
    "nome" : "Brasil, a maior escola criativa do mundo",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 42,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=XGSYyXV06To",
    "img" : "https://i.ytimg.com/vi/XGSYyXV06To/hqdefault.jpg"
  },
  "2023-08-19-019" : {
    "nome" : "Se o Brasil fosse um metaverso, como seria?",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 41,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=vQ2NjODyzDU",
    "img" : "https://i.ytimg.com/vi/vQ2NjODyzDU/hqdefault.jpg"
  },
  "2023-08-19-020" : {
    "nome" : "O poder dos territórios circulares",
    "produtoras" : ["Transcriativa","TV Cultura Mineira"],
    "programa" : "Palco Podcast",
    "formato" : "vídeo",
    "data" : "2023-08-19",
    "duracao" : 46,
    "plataformas" : ["YouTube","Facebook"],
    "link" : "https://www.youtube.com/watch?v=oldab7NTqLA",
    "img" : "https://i.ytimg.com/vi/oldab7NTqLA/hqdefault.jpg"
  },
  "2023-08-20-001" : {
    "nome" : "Hacktalks em 15 minutos com Bruno Orlandi, direto do Hacktown 2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Hacktalks em 15 minutos",
    "formato" : "vídeo",
    "data" : "2023-08-20",
    "duracao" : 16,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=zMKhofbfPcs",
    "img" : "https://i.ytimg.com/vi/zMKhofbfPcs/hqdefault.jpg"
  },
  "2023-08-20-002" : {
    "nome" : "Hacktalks em 15 minutos com Giovanni Bassi, direto do Hacktown 2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Hacktalks em 15 minutos",
    "formato" : "vídeo",
    "data" : "2023-08-20",
    "duracao" : 15,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=Q0ByYJuRQg0",
    "img" : "https://i.ytimg.com/vi/Q0ByYJuRQg0/hqdefault.jpg"
  },
  "2023-08-20-003" : {
    "nome" : "Giro Hacktalks by Compasso Coolab - 20ago2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Giro Hacktalks",
    "formato" : "vídeo",
    "data" : "2023-08-20",
    "duracao" : 4,
    "plataformas" : ["YouTube","Instagram"],
    "link" : "https://www.youtube.com/watch?v=wIbewqDV06w",
    "img" : "https://img.youtube.com/vi/wIbewqDV06w/maxresdefault.jpg"
  },
  "2023-08-20-004" : {
    "nome" : "Jeferson Padilha e Michel Couto No Hacktown 2023 - Rock Night Podcast #03",
    "produtoras" : ["Rock Night","Conta pro Queiroz"],
    "programa" : "Rock Night",
    "formato" : "vídeo",
    "data" : "2023-08-20",
    "duracao" : 69,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=Hs_LduWDX6s",
    "img" : "https://i.ytimg.com/vi/Hs_LduWDX6s/hqdefault.jpg"
  },
  "2023-08-21-001" : {
    "nome" : "Hacktalks em 15 minutos com Andrea Martinelli, direto do Hacktown 2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Hacktalks em 15 minutos",
    "formato" : "vídeo",
    "data" : "2023-08-21",
    "duracao" : 16,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=Pq3B1QHBaGc",
    "img" : "https://img.youtube.com/vi/Pq3B1QHBaGc/maxresdefault.jpg"
  },
  "2023-08-21-002" : {
    "nome" : "Hacktalks em 15 minutos com Guilherme Moraes, direto do Hacktown 2023",
    "produtoras" : ["Compasso Coolab"],
    "programa" : "Hacktalks em 15 minutos",
    "formato" : "vídeo",
    "data" : "2023-08-21",
    "duracao" : 13,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=sVwXgT7_f14",
    "img" : "https://i.ytimg.com/vi/sVwXgT7_f14/hqdefault.jpg"
  },
  "2023-08-22-001" : {
    "nome" : "APPCast #138 - Hacktown 2023 ",
    "produtoras" : ["Compasso Coolab","Associação de Profissionais de Propaganda"],
    "programa" : "APP Cast",
    "formato" : "vídeo",
    "data" : "2023-08-22",
    "duracao" : 53,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=kGhZe9j81-A",
    "img" : "https://i.ytimg.com/vi/kGhZe9j81-A/hqdefault.jpg"
  },
  "2023-08-23-001" : {
    "nome" : "BTec no Hacktown SRS 2023",
    "produtoras" : ["Incubadora BTec"],
    "programa" : "Talk BTec",
    "formato" : "audio",
    "data" : "2023-08-23",
    "duracao" : 6,
    "plataformas" : ["Spotify"],
    "link" : "https://open.spotify.com/episode/2tIy7CtKUGBp20slLxKKZ0",
    "img" : "https://i.scdn.co/image/ab67656300005f1f5d8f8d797eceae60803eaadc"
  },
  "2023-08-24-001" : {
    "nome" : " Arena de Ideias #117 | Download HackTown SRS 2023 ",
    "produtoras" : ["Oficina Consultoria de Reputação e Gestão de Relacionamento"],
    "programa" : "Arena de Ideias",
    "formato" : "vídeo",
    "data" : "2023-08-24",
    "duracao" : 60,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=cpF2hH0zDBg",
    "img" : "https://i.ytimg.com/vi/cpF2hH0zDBg/hqdefault.jpg"
  },
  "2023-08-24-002" : {
    "nome" : "Como RECEBER INVESTIMENTO DO GOVERNO para o seu NEGÓCIO EM SOFTWARE",
    "produtoras" : ["DevPleno"],
    "programa" : "DevPleno",
    "formato" : "vídeo",
    "data" : "2023-08-24",
    "duracao" : 11,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=G8nn_7l_SzU",
    "img" : "https://i.ytimg.com/vi/G8nn_7l_SzU/hqdefault.jpg"
  },
  "2023-08-25-001" : {
    "nome" : "🔥TrenDs News🚀 #94",
    "produtoras" : ["🚀 TrenDs News 🔥"],
    "programa" : "🚀 TrenDs News 🔥",
    "formato" : "vídeo",
    "data" : "2023-08-25",
    "duracao" : 66,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=JE2Wj4fWpio",
    "img" : "https://i.ytimg.com/vi/JE2Wj4fWpio/hqdefault.jpg"
  },
  "2023-08-29-001" : {
    "nome" : "Revolucione sua vida e carreira: Seja fora da caixa e tenha um propósito vital! — HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-08-29",
    "duracao" : 28,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=bMQ_2Uu7s28",
    "img" : "https://i.ytimg.com/vi/bMQ_2Uu7s28/hqdefault.jpg"
  },
  "2023-08-29-002" : {
    "nome" : "Descubra as novidades de inovação com a Ambev no HackTown 2023!",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-08-29",
    "duracao" : 28,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=UG32UNHSwO0",
    "img" : "https://i.ytimg.com/vi/UG32UNHSwO0/hqdefault.jpg"
  },
  "2023-08-29-003" : {
    "nome" : "Como o autocontrole pode mudar o seu comportamento no mundo profissional? — HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-08-29",
    "duracao" : 26,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=t_5Ae9mTLAU",
    "img" : "https://i.ytimg.com/vi/t_5Ae9mTLAU/hqdefault.jpg"
  },
  "2023-08-29-004" : {
    "nome" : "Futurês #2 - Decodificando o Futuro no Hacktown 2023 de Santa Rita do Sapucaí",
    "produtoras" : ["Futuros Plurais"],
    "programa" : "Futurês",
    "formato" : "vídeo",
    "data" : "2023-08-29",
    "duracao" : 66,
    "plataformas" : ["Spotify","YouTube"],
    "link" : "https://www.youtube.com/watch?v=PwUwJRoDWYw",
    "img" : "https://i.scdn.co/image/ab67656300005f1fb4478095d12b814870d94416"
  },
  "2023-08-30-001" : {
    "nome" : "Inovação e estratégias com Leandro Ferreira, da MOV Locadora - HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-08-30",
    "duracao" : 22,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=Kq7r-9q9gTg",
    "img" : "https://i.ytimg.com/vi/Kq7r-9q9gTg/hqdefault.jpg"
  },
  "2023-08-30-002" : {
    "nome" : "Como a Inovação está moldando o mundo em que vivemos? — HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-08-30",
    "duracao" : 34,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=K9-l0YF-TjA",
    "img" : "https://i.ytimg.com/vi/K9-l0YF-TjA/hqdefault.jpg"
  },
  "2023-08-30-003" : {
    "nome" : "Será que marcas consolidadas ainda têm o poder de inovar? Descubra Aqui! — HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-08-30",
    "duracao" : 25,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=QmROpLGCim4",
    "img" : "https://i.ytimg.com/vi/QmROpLGCim4/hqdefault.jpg"
  },
  "2023-08-30-005" : {
    "nome" : "Como Nathalia Arcuri ajudou milhares de pessoas com educação financeira? HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-08-30",
    "duracao" : 32,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=wQ7sv6Nfekc",
    "img" : "https://i.ytimg.com/vi/wQ7sv6Nfekc/hqdefault.jpg"
  },
    "2023-08-31-001" : {
    "nome" : "Como o ChatGPT e outras ferramentas de IA auxiliam nos processos de inovação? - HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-08-31",
    "duracao" : 34,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=z5nAdjfJJCY",
    "img" : "https://img.youtube.com/vi/z5nAdjfJJCY/maxresdefault.jpg"
  },
  "2023-08-31-002" : {
    "nome" : "IA, computação quântica e tecnologias emergentes no processo de inovação - HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-08-31",
    "duracao" : 23,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=E3dOtniZJW0",
    "img" : "https://img.youtube.com/vi/E3dOtniZJW0/maxresdefault.jpg"
  },
  "2023-08-31-003" : {
    "nome" : "Todo empreendedor que deseja ter sucesso precisa assistir a esse vídeo! — HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-08-31",
    "duracao" : 24,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=rff0bVpj2u0",
    "img" : "https://img.youtube.com/vi/rff0bVpj2u0/maxresdefault.jpg"
  },
  "2023-08-31-004" : {
    "nome" : "O que esperar do futuro do marketing e da tecnologia no Brasil? - HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-08-31",
    "duracao" : 26,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=y60JVhC5AdA",
    "img" : "https://img.youtube.com/vi/y60JVhC5AdA/maxresdefault.jpg"
  },
  "2023-09-01-001" : {
    "nome" : "Hacktown 2023, uma Jornada de inovação e conexão humana!",
    "produtoras" : ["Mind Station"],
    "programa" : "Mind Station",
    "formato" : "vídeo",
    "data" : "2023-09-01",
    "duracao" : 8,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=Ie7y_ppmb98",
    "img" : "https://i.ytimg.com/vi/Ie7y_ppmb98/hqdefault.jpg"
  },
  "2023-09-02-001" : {
    "nome" : " #003 - Insights & Reflexões do Hack Town 2023 ",
    "produtoras" : ["Hyper Island"],
    "programa" : "Hyper Vision Podcast",
    "formato" : "vídeo",
    "data" : "2023-09-02",
    "duracao" : 48,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=zyh9MfLSJaA",
    "img" : "https://i.ytimg.com/vi/zyh9MfLSJaA/hqdefault.jpg"
  },
  "2023-09-04-001" : {
    "nome" : "HackTown 2023: Inovações que vão mudar o mundo!",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-09-04",
    "duracao" : 38,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=C1pKCv3K0EU",
    "img" : "https://img.youtube.com/vi/C1pKCv3K0EU/maxresdefault.jpg"
  },
  "2023-09-04-002" : {
    "nome" : "Esse papo vai mudar a sua visão sobre o mundo! — HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-09-04",
    "duracao" : 32,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=azPnKI0EojE",
    "img" : "https://img.youtube.com/vi/azPnKI0EojE/maxresdefault.jpg"
  },
  "2023-09-04-003" : {
    "nome" : "Segredos e estratégias de segurança da informação no HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-09-04",
    "duracao" : 26,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=QVgQn6TN3hQ",
    "img" : "https://img.youtube.com/vi/QVgQn6TN3hQ/maxresdefault.jpg"
  },
  "2023-09-04-004" : {
    "nome" : "Como a Claro está inovando o setor financeiro? - HackTown 2023 com Maurício Santos",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-09-04",
    "duracao" : 18,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=RelCyrOF-wk",
    "img" : "https://img.youtube.com/vi/RelCyrOF-wk/maxresdefault.jpg"
  },
  "2023-09-04-005" : {
    "nome" : "beOn Claro e Monking no HackTown 2023 | Episódio 1 | Encruzilhadas da Inovação",
    "produtoras" : ["Monking","Claro"],
    "programa" : "BeOn HackTown 2023",
    "formato" : "vídeo",
    "data" : "2023-09-04",
    "duracao" : 32,
    "plataformas" : ["YouTube","Spotify","Claro Musica"],
    "link" : "https://www.youtube.com/watch?v=O3b76dmzq7s",
    "img" : "https://i.ytimg.com/vi/O3b76dmzq7s/hqdefault.jpg"
  },
  "2023-09-04-006" : {
    "nome" : "beOn Claro e Monking no HackTown 2023 | Episódio 2 | Cybersecurity - próximo nível da Inovação",
    "produtoras" : ["Monking","Claro"],
    "programa" : "BeOn HackTown 2023",
    "formato" : "vídeo",
    "data" : "2023-09-04",
    "duracao" : 27,
    "plataformas" : ["YouTube","Spotify","Claro Musica"],
    "link" : "https://www.youtube.com/watch?v=_L2IsiYZrw8",
    "img" : "https://i.ytimg.com/vi/_L2IsiYZrw8/hqdefault.jpg"
  },
  "2023-09-04-007" : {
    "nome" : "beOn Claro e Monking no HackTown 2023 | Episódio 3 | Claro no mercado de serviço financeiro",
    "produtoras" : ["Monking","Claro"],
    "programa" : "BeOn HackTown 2023",
    "formato" : "vídeo",
    "data" : "2023-09-04",
    "duracao" : 19,
    "plataformas" : ["YouTube","Spotify","Claro Musica"],
    "link" : "https://www.youtube.com/watch?v=Q6pJXG0UYmo",
    "img" : "https://i.ytimg.com/vi/Q6pJXG0UYmo/hqdefault.jpg"
  },
  "2023-09-04-008" : {
    "nome" : "beOn Claro e Monking no HackTown 2023 | Episódio 4 | A Cidade é a Plataforma",
    "produtoras" : ["Monking","Claro"],
    "programa" : "BeOn HackTown 2023",
    "formato" : "vídeo",
    "data" : "2023-09-04",
    "duracao" : 32,
    "plataformas" : ["YouTube","Spotify","Claro Musica"],
    "link" : "https://www.youtube.com/watch?v=hYGU8lufxe4",
    "img" : "https://i.ytimg.com/vi/hYGU8lufxe4/hqdefault.jpg"
  },
  "2023-09-05-001" : {
    "nome" : "Qual é o papel do Hacktown para a inovação brasileira?",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-09-05",
    "duracao" : 32,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=idFVr-y4oqU",
    "img" : "https://img.youtube.com/vi/idFVr-y4oqU/maxresdefault.jpg"
  },
  "2023-09-05-002" : {
    "nome" : "Como a comunidade de startups está revolucionando o mundo corporativo? — HackTown 2023",
    "produtoras" : ["Monking","Claro"],
    "programa" : "Monking no HackTown",
    "formato" : "vídeo",
    "data" : "2023-09-05",
    "duracao" : 35,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=l84h6lJoyDI",
    "img" : "https://img.youtube.com/vi/l84h6lJoyDI/maxresdefault.jpg"
  },
  "2023-09-06-001" : {
    "nome" : "Aprendizados do HackTown - Hora da Conexão, com Alice Salvo e Cássia Aulisio",
    "produtoras" : ["Liga dos Inovadores","Somos Curatas"],
    "programa" : "Hora da Conexão",
    "formato" : "vídeo",
    "data" : "2023-09-06",
    "duracao" : 68,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=6_xz_hzH1fc",
    "img" : "https://img.youtube.com/vi/6_xz_hzH1fc/maxresdefault.jpg"
  },
  "2023-09-06-002" : {
    "nome" : "Vinicius Piva Conta como Foi o HackTown",
    "produtoras" : ["TV Cidade Farroupilha"],
    "programa" : "Resolvendo Dilemas",
    "formato" : "vídeo",
    "data" : "2023-09-06",
    "duracao" : 28,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=1FHztI_IEmo",
    "img" : "https://img.youtube.com/vi/1FHztI_IEmo/maxresdefault.jpg"
  },
  "2023-09-07-001" : {
    "nome" : "#38 Construindo um ecossistema de inovação: as experiências da Campinas Tech",
    "produtoras" : ["Performa_IT","Hyper Island"],
    "programa" : "Performa.Que.Pod.",
    "formato" : "vídeo",
    "data" : "2023-09-07",
    "duracao" : 49,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=bYxdIfmTLBE",
    "img" : "https://img.youtube.com/vi/bYxdIfmTLBE/maxresdefault.jpg"
  },
  "2023-09-11-001" : {
    "nome" : "[TEMPORADA 2 - Episódio 16] - Insights do HackTown 2023",
    "produtoras" : ["Somos Curatas"],
    "programa" : "Videocast Somos Curatas",
    "formato" : "vídeo",
    "data" : "2023-09-11",
    "duracao" : 35,
    "plataformas" : ["YouTube"],
    "link" : "https://www.youtube.com/watch?v=11YB8rNGEuc",
    "img" : "https://img.youtube.com/vi/11YB8rNGEuc/maxresdefault.jpg"
  },
  "2023-09-14-001" : {
    "nome" : "#39 Palcos nacionais, conexões globais: Edição Especial HackTown",
    "produtoras" : ["Performa_IT","Hyper Island"],
    "programa" : "Performa.Que.Pod.",
    "formato" : "vídeo",
    "data" : "2023-09-14",
    "duracao" : 40,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=J7fq4-EEwRM",
    "img" : "https://img.youtube.com/vi/J7fq4-EEwRM/maxresdefault.jpg"
  },
  "2023-10-03-001" : {
    "nome" : "HackTown: Uma experiência inesquecível",
    "produtoras" : ["Claro","Deloitte"],
    "programa" : "BeOn Claro",
    "formato" : "vídeo",
    "data" : "2023-10-03",
    "duracao" : 21,
    "plataformas" : ["YouTube","Spotify"],
    "link" : "https://www.youtube.com/watch?v=8nPqT8p3zSE",
    "img" : "https://i.ytimg.com/vi/8nPqT8p3zSE/hqdefault.jpg"
  }
};
